apiVersion: apps/v1
kind: Deployment
metadata:
  name: expresssimple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expresssimple
  template:
    metadata:
      labels:
        app: expresssimple
    spec:
      containers:
      - name: expresssimple
        image: ghcr.io/ant2br/expresssimple:latest
        ports:
        - containerPort: 3000