apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: expresssimple-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: expresssimple
  minReplicas: 2
  maxReplicas: 5
