apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: hml

images:
- name: expresssimple
  newName: ghcr.io/ant2br/expresssimple
  newTag: latest
- name: ghcr.io/ant2br/expresssimple
  newTag: 82bbcf6cbb5a09646e982e07806c3ae243de85c4
