name: CI

on:
  push:
    branches:
      - main
  
  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.ACTOR }}
        password: ${{ secrets.TOKEN }}
    
    - run: |
        docker build -t ghcr.io/ant2br/expresssimple:latest -f Dockerfile .
        docker tag ghcr.io/ant2br/expresssimple:latest ghcr.io/ant2br/expresssimple:${{ github.sha }}
    
    - run: |
        docker push ghcr.io/ant2br/expresssimple:latest
        docker push ghcr.io/ant2br/expresssimple:${{ github.sha }}


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1
      - name: update k8s 
        run: |
          cd k8s
          kustomize edit set image ghcr.io/ant2br/expresssimple:${{ github.sha }}

      - name: commit 
        run: |
          git config --local user.email "gitops@brener.dev"
          git config --local user.name "GitOps"
          git commit -am "Update image to ${{ github.sha }}"

      - name: push 
        uses: ad-m/github-push-action@master


          
    