on: 
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone"
      - uses: actions/checkout@v2

      - name: "Login"
      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: $ACTOR
          password: $TOKEN

      - name: "Build"
      - run: |
          docker build -t ghcr.io/ant2br/docker/ant2br:latest -f Dockerfile .
          docker tag ghcr.io/ant2br/docker/ant2br:latest ghcr.io/ant2br/docker/ant2br:$GITHUB_SHA

      - name: "Push"
      - run: |
          docker push ghcr.io/ant2br/docker/ant2br:latest
          docker push ghcr.io/ant2br/docker/ant2br:$GITHUB_SHA
